name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['stable']
        test_engine: ['1testrunner']
        include:
          - oscript_version: 'dev'
            test_engine: 'oneunit'
    uses: autumn-library/workflows/.github/workflows/test.yml@v1
    with:
      oscript_version: ${{ matrix.oscript_version }}
      test_engine: ${{ matrix.test_engine }}
      dotnet_version: "8.x.x"
      build_package: true